name: rust

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 0 1 * *
  pull_request:
    branches: [ main ]

env:
  CARGO_INCREMENTAL: 1

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            lint: 1

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: cargo build
        run: cargo build --workspace --all-features

      - name: cargo test
        run: cargo test --workspace --all-features

      - name: cargo fmt
        if: github.event_name == 'pull_request' && matrix.lint
        run: cargo fmt --all -- --check

      - name: cargo clippy
        if: github.event_name == 'pull_request' && matrix.lint
        run: cargo clippy --workspace --all-features --tests -- -D warnings
